### ISSUE TITLE
distribute prebuild timeswipe pip module for arm 32 and 64

### ISSUE THREAD

**Issue by iluxa** [panda-official/TimeSwipe.py#2]

**Comment by IngoKaiser** [comment]
Will be added to https://pypi.org right?

**Comment by iluxa** [comment]
yes, it is supposed to be added to pypi

**Comment by iluxa** [comment]
PR for precompiled binaries:
https://github.com/panda-official/TimeSwipe.py/pull/4

PyPi supports platform **linux_armv7l**, but it doesn't support platform **linux_aarch64**
so, it can be better to put releases to github [releases] (https://github.com/panda-official/TimeSwipe.py/releases) and install with `sudo pip3 install <uri>` as described in README.md

**Comment by iluxa** [comment]
github CI/CD implemented Readme updated accordingly

**Comment by IngoKaiser** [comment]
worked for me.
